# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beyond Management' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beyond Management
pod 'Alamofire', '~> 4.3'
pod 'SDWebImage/WebP', '~>3.8'

end
