# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beyond Management' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beyond Management
pod 'Alamofire', '~> 4.3'
pod 'SDWebImage/WebP', '~>3.8'
pod 'BraintreeDropIn'
pod 'Braintree/PayPal'
pod 'Braintree/Apple-Pay'
pod 'SideMenu'

pod 'Firebase/Core'
pod 'Fabric', '~> 1.7.2'
pod 'Crashlytics', '~> 3.9.3'

end
